[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"